name: Auto Sync and Remove BaseURL

on:
  push:
    branches: [ master ]

jobs:
  sync-and-remove-baseurl:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync master branch to no-base-url-branch
        run: |
          # 强制创建/更新 no-base-url-branch 为 master 的副本
          git checkout master
          git branch -D no-base-url-branch || true
          git checkout -b no-base-url-branch
          
          # 修改配置文件
          sed -i '/baseURL:/c\    // baseURL: removed for this branch,' nuxt.config.ts
          
          # 提交更改
          git add nuxt.config.ts
          git commit -m "chore: sync from master and remove baseURL"
          
          # 强制推送更新
          git push -f origin no-base-url-branch